name: Fast-Forward

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  fast-forward:
    name: Fast-Forward
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.REPOSITORY_TOKEN }}
      - name: Fast-Forward
        run: |
          git remote add upstream https://github.com/vlang/vinix.git
          git pull --ff-only upstream main
          git push origin main